import type { NextPage } from "next";
import Head from "next/head";
import SummonerSearch from "../components/summonerSearch";
import ProfileSummaryCard from "~/components/profileSummaryCard";

const Home: NextPage = () => {
  const puuids = [
    "Uvx0KFVS5DrrvFAc52iU4MA17R3RbtEU7PoIC4vZbXparKFupxoDyCGXoVz-KSYWT0TnfyAQE9lAOw",
    "x0U9ERlX4M2QaHdpR522a_9g47NkI8ou-yZ7ec4qhNlsUkH4Nfypatq4yl0BTBStEDb9owLU2L5q3w",
    "ET9mTh-cnH0yqBKrRX9XZEtQJz1cTMPuB46AyctUc858sBkKOJCXw151FXvRPnyus-NSBoki2EnL3Q",
    "JgnblmPcwrZP6Mrj2tToHJVCo_1Q99G_qpN5MjAbt3wgsiD6jtBfsnfX7r0qcO6o9EuSYn0JNPWZnw",
  ];

  return (
    <>
      <Head>
        <title>TFT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center gap-8 bg-zinc-900">
        <div className="flex w-full justify-center border-b border-zinc-950 p-2">
          <SummonerSearch />
        </div>
        <ul className="grid grid-cols-3 gap-4">
          {puuids.map((puuid) => (
            <li key={puuid}>
              <ProfileSummaryCard summoner_puuid={puuid} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
